#######################################################################
# Copyright (C) 2017 Shangtong Zhang(zhangshangtong.cpp@gmail.com)    #
# Permission given to modify the code as long as you keep this        #
# declaration at the top                                              #
#######################################################################

from ..network import *
from ..component import *
from .BaseAgent import *

from datetime import datetime
import matplotlib.image as imag
def timestamp():
    now = datetime.now()
    return now.strftime("%m%d %H-%M-%S")

class WOKSPPOAgent(BaseAgent):
    def __init__(self, config):
        BaseAgent.__init__(self, config)
        self.config = config
        self.task = config.task_fn()
        self.num_agents = config.num_workers
        self.network = config.network_fn(self.task.state_dim, self.task.action_dim, self.config.cl_num_tasks)
        # self.network = config.network_fn(self.task.state_dim, self.task.action_dim, self.config.cl_num_tasks)
        self.optimizer = config.optimizer_fn(self.network.parameters())
        self.total_steps = 0
        # self.states = np.array([x[0] for x in self.task.reset()])
        self.states = np.array([x for x in self.task.reset()])
        #self.states = config.state_normalizer(self.states)
        if len(self.states[0].shape)<3:
            self.states = config.state_normalizer(np.expand_dims(self.states, axis=1))
        else:
            self.states = config.state_normalizer(self.states)
        self.episode_rewards = np.zeros(config.num_workers)
        self.last_episode_rewards = np.zeros(config.num_workers)

    def iteration(self, task_label=None, labels_set=None, learn=True):
        """
        actions_list stores the action taken at each timestep.
        states_info_list stores the phi/latent space at each timestep.
        reward_list stores reward at each timestep.
        values_list stores for each possible task, the value generated by the agent.
        """
        config = self.config
        rollout = []
        obs = []
        actions_list = []
        states_info_list = []
        reward_list = []
        values_list = [[] for _ in range(len(labels_set))]
        self.episode_rewards = np.zeros(self.num_agents)
        self.last_episode_rewards = np.zeros(self.num_agents)
        for jj in range(config.rollout_length):
            for idx, each_label in enumerate(labels_set):
                with torch.no_grad():
                    _, _, _, _, swoks_vals, _ = self.network.predict(self.states, task_label=each_label.tolist())
                values_list[idx].append(swoks_vals.detach().cpu().numpy())

            _, actions, log_probs, entropy, values, supp_info = self.network.predict(self.states, task_label=task_label)


            actions_list.append(actions.detach().cpu().numpy())
            states_info_list.append(supp_info.detach().cpu().numpy())
            next_states, rewards, terminals, *_ = self.task.step(actions.detach().cpu().numpy())
            if len(next_states[0].shape)<3:
                next_states = config.state_normalizer(np.expand_dims(next_states, axis=1))
            else:
                next_states = config.state_normalizer(next_states)
            reward_list.append(rewards)
            self.episode_rewards += rewards
            rewards = config.reward_normalizer(rewards)
            for i, terminal in enumerate(terminals):
                if terminals[i]:
                    self.last_episode_rewards[i] = self.episode_rewards[i]
                    self.episode_rewards[i] = 0


            rollout.append([np.copy(self.states), actions.detach(), log_probs.detach(), values.detach(), actions, rewards, 1 - terminals, entropy])
            self.states = next_states
            obs.append(next_states)
        pending_value = self.network.predict(self.states, task_label=task_label)[-2]
        rollout.append([None, pending_value, None, None, None, None])

        processed_rollout = [None] * (len(rollout) - 1)
        advantages = tensor(np.zeros((config.num_workers, 1)))
        returns = pending_value.detach()
        for i in reversed(range(len(rollout) - 1)):
            state, actions, log_prob, value, actions, rewards, terminals, entropy = rollout[i]
            state = tensor(state)
            actions = tensor(actions)
            terminals = tensor(terminals).unsqueeze(1)
            rewards = tensor(rewards).unsqueeze(1)
            next_value = rollout[i + 1][1]
            returns = rewards + config.discount * terminals * returns
            if not config.use_gae:
                advantages = returns - value.squeeze(1).detach()
            else:
                td_error = rewards + config.discount * terminals * next_value.detach() - value.detach()
                advantages = advantages * config.gae_tau * config.discount * terminals + td_error
            processed_rollout[i] = [state, actions, log_prob, value, returns, advantages, entropy]

        state, actions, log_prob, value, returns, advantages, entropy = map(lambda x: torch.cat(x, dim=0), zip(*processed_rollout))

        batcher = Batcher(state.size(0) // config.num_mini_batches, [np.arange(state.size(0))])
        for _ in range(5): #optimisation epochs
            batcher.shuffle()
            while not batcher.end():
                batch_indices = batcher.next_batch()[0]
                batch_indices = tensor(batch_indices).long()
                sampled_states = state[batch_indices]
                sampled_actions = actions[batch_indices]
                sampled_log_probs_old = log_prob[batch_indices]
                sampled_returns = returns[batch_indices]
                sampled_advantages = advantages[batch_indices]

                _, _, logprob, entloss, vals, _ = self.network.predict(sampled_states, action=sampled_actions, task_label=task_label)
                ratio = (logprob - sampled_log_probs_old).exp()
                obj = ratio * sampled_advantages
                obj_clipped = ratio.clamp(1.0 - self.config.ppo_ratio_clip,
                                          1.0 + self.config.ppo_ratio_clip) * sampled_advantages
                policy_loss = -torch.min(obj, obj_clipped).mean(0) - config.entropy_weight * entloss.mean()

                value_loss = 0.5 * (sampled_returns - vals).pow(2).mean()

                if learn:
                    self.optimizer.zero_grad()
                    (policy_loss + value_loss).sum().backward()
                    nn.utils.clip_grad_norm_(self.network.parameters(), config.gradient_clip)
                    self.optimizer.step()

        steps = config.rollout_length * config.num_workers
        self.total_steps += steps
        self.loss = (policy_loss + value_loss).sum()

        # with the block of code below, rows are workers, columns are actions/states_info for 
        # each worker in rollout_length of the iteration.
        actions_list = np.array(actions_list).T
        states_info_list = np.swapaxes(np.array(states_info_list), 0, 1)
        reward_list = np.array(reward_list).T
        return actions_list, states_info_list, reward_list, values_list


class PPOAgent(BaseAgent):
    def __init__(self, config):
        BaseAgent.__init__(self, config)
        self.config = config
        self.task = config.task_fn()
        self.network = config.network_fn(self.task.state_dim, self.task.action_dim)
        self.opt = config.optimizer_fn(self.network.parameters())
        self.total_steps = 0
        self.episode_rewards = np.zeros(config.num_workers)
        self.last_episode_rewards = np.zeros(config.num_workers)
        self.states = self.task.reset()
        self.states = config.state_normalizer(self.states)

    def iteration(self):
        config = self.config
        rollout = []
        states = self.states
        for _ in range(config.rollout_length):
            actions, log_probs, _, values = self.network.predict(states)
            next_states, rewards, terminals, *_ = self.task.step(actions.cpu().detach().numpy())
            self.episode_rewards += rewards
            rewards = config.reward_normalizer(rewards)
            for i, terminal in enumerate(terminals):
                if terminals[i]:
                    self.last_episode_rewards[i] = self.episode_rewards[i]
                    self.episode_rewards[i] = 0
            next_states = config.state_normalizer(next_states)
            rollout.append([states, values.detach(), actions.detach(), log_probs.detach(), rewards, 1 - terminals])
            states = next_states

        self.states = states
        pending_value = self.network.predict(states)[-1]
        rollout.append([states, pending_value, None, None, None, None])
        processed_rollout = [None] * (len(rollout) - 1)
        advantages = tensor(np.zeros((config.num_workers, 1)))
        returns = pending_value.detach()
        for i in reversed(range(len(rollout) - 1)):
            states, value, actions, log_probs, rewards, terminals = rollout[i]
            terminals = tensor(terminals).unsqueeze(1)
            rewards = tensor(rewards).unsqueeze(1)
            actions = tensor(actions)
            states = tensor(states)
            next_value = rollout[i + 1][1]
            returns = rewards + config.discount * terminals * returns
            if not config.use_gae:
                advantages = returns - value.detach()
            else:
                td_error = rewards + config.discount * terminals * next_value.detach() - value.detach()
                advantages = advantages * config.gae_tau * config.discount * terminals + td_error
            processed_rollout[i] = [states, actions, log_probs, returns, advantages]

        states, actions, log_probs_old, returns, advantages = map(lambda x: torch.cat(x, dim=0), zip(*processed_rollout))
        advantages = (advantages - advantages.mean()) / advantages.std()

        batcher = Batcher(states.size(0) // config.num_mini_batches, [np.arange(states.size(0))])
        for _ in range(config.optimization_epochs):
            batcher.shuffle()
            while not batcher.end():
                batch_indices = batcher.next_batch()[0]
                batch_indices = tensor(batch_indices).long()
                sampled_states = states[batch_indices]
                sampled_actions = actions[batch_indices]
                sampled_log_probs_old = log_probs_old[batch_indices]
                sampled_returns = returns[batch_indices]
                sampled_advantages = advantages[batch_indices]

                _, log_probs, entropy_loss, values = self.network.predict(sampled_states, sampled_actions)
                ratio = (log_probs - sampled_log_probs_old).exp()
                obj = ratio * sampled_advantages
                obj_clipped = ratio.clamp(1.0 - self.config.ppo_ratio_clip,
                                          1.0 + self.config.ppo_ratio_clip) * sampled_advantages
                policy_loss = -torch.min(obj, obj_clipped).mean(0) - config.entropy_weight * entropy_loss.mean()

                value_loss = 0.5 * (sampled_returns - values).pow(2).mean()

                self.opt.zero_grad()
                (policy_loss + value_loss).backward()
                nn.utils.clip_grad_norm_(self.network.parameters(), config.gradient_clip)
                self.opt.step()

        steps = config.rollout_length * config.num_workers
        self.total_steps += steps
